name: AvocADO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  branch-name: ${GITHUB_REF#refs/heads/}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
        with:
          java-version: 11
      - run: sbt test
